name: GitHub Classroom Autograding
on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Grading Script
        id: grading
        run: python3 tests/grading.py

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          GRADING_RESULTS: ${{ steps.grading.outputs.result }}
        with:
          runners: grading
