name: GitHub Classroom Autograding
on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Grading Script
        uses: education/autograding-command-grader@v1
        id: grading
        with:
          test-name: Consistency Logic Check
          command: python3 tests/grading.py
          timeout: 10
          max-score: 100

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        with:
          runners: grading
